# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink: /:year/:month/:day/:title/

# Setup
title:            Fagner
tagline:          'Just another day in IT.'
description: >
    Hello, welcome!<br/>
    Here I share everything that I learnt (or not).<br/>
    Have a good stay!<br/>
url:              http://fagner.co
baseurl:          /

author:
  name:           'Fagner Carvalho'
  url:            https://twitter.com/fagnerncarvalho

paginate:         5

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
  - pygments.rb
  - classifier-reborn

# Custom vars
version:          3.0

github:
  repo:           https://github.com/fagnercarvalho

disqus:           fagnerblog
