# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: /:year/:month/:day/:title
relative_permalinks: true

# Setup
title:            Fagner
tagline:          'Just another day in IT.'
description: >
    Hello, welcome!<br/>
    Here I share everything that I learnt (or not).<br/>
    Have a good stay!<br/>
url:              http://fagner.co
baseurl:          /

author:
  name:           'Fagner Carvalho'
  url:            https://twitter.com/fagnerncarvalho

paginate:         5

gems:
  - jekyll-redirect-from

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fagnercarvalho

disqus:           fagnerblog
