name: Fagner Carvalho
description: Just another day in IT
meta_description: "Fagner Carvalho: just another day in IT"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 10
baseurl: /
domain_name: 'fagner.co'

# Details for the RSS feed generator
url:            'fagner.co'
author:         'Fagner Carvalho'

page:
  disqus:           fagnerblog

# Owner/author information
owner:
  name:           Fagner Carvalho
  description:	  I simply another passionate about new technologies and the things that you can do with it. 
  avatar:         /assets/images/profile.jpg
  email:          fagnerncarvalho@gmail.com
  github:         https://github.com/fagnercarvalho
  google_plus:    https://plus.google.com/111373715138599649043